### ISSUE TITLE
Startup Optimiser 3.5.0 not working with 4.8 release version

### ISSUE THREAD

**Issue by Thisismydigitalself** [fieldOfView/Cura-StartOptimiser#3]
same goes for 4.8beta. it does work with 4.7.0
![ice_screenshot_20201110-174710](https://user-images.githubusercontent.com/30949968/98698126-6149a580-237e-11eb-9ccc-0c7a5b2fc7b1.png)

**Comment by fieldOfView** [comment]
Please describe what is not working. The screenshot shows a button that is provided by the plugin, so for all I know the plugin *is* working.

**Comment by Thisismydigitalself** [comment]
Unlike with 4.7.x, with 4.8beta/release, each time i launch cura i get this error message. i disable affected profile, but next time i launch cura i get this same message.

**From Cura log:**
2020-11-10 17:42:40,900 - INFO - [MainThread] StartOptimiser.StartOptimiser.init [40]: 10 containers are blacklisted by StartOptimiser
2020-11-10 17:42:40,900 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin StartOptimiser

**From Cura cfg:**
[start_optimiser]
container_blacklist = ;custom_extruder_1 #12;custom_extruder_8 #13;custom_extruder_6 #9;custom_extruder_3 #3;custom_extruder_4 #7;custom_extruder_7 #6;custom_extruder_2 #7;custom_extruder_6 #12;custom_extruder_5 #2



![98698126-6149a580-237e-11eb-9ccc-0c7a5b2fc7b1](https://user-images.githubusercontent.com/30949968/98701889-70caed80-2382-11eb-8705-3aa79e8f1916.png)
![ice_screenshot_20201110-182942](https://user-images.githubusercontent.com/30949968/98702156-be475a80-2382-11eb-90f3-b686f252e761.png)

But everytime i launch Cura 4.8 - this configuration errors message keeps popping up.

**Comment by Thisismydigitalself** [comment]
2020-11-10 17:42:40,900 - INFO - [MainThread] StartOptimiser.StartOptimiser.__init__ [40]: 10 containers are blacklisted by StartOptimiser
2020-11-10 17:42:40,900 - INFO - [MainThread] UM.Logger.info [122]: Loaded plugin StartOptimiser

**Comment by fieldOfView** [comment]
> But everytime i launch Cura 4.8 - this configuration errors message keeps popping up.

Is the error message showing the same profiles (ie: are the numbers after custom_extruder the same?)

Could you zip up your entire configuration folder and share a link to the zip at aldo [at] fieldofview [dot] com ?

**Comment by Thisismydigitalself** [comment]
Hello Aldo, I ended up manually deleting all 9 configurations (hundreds of related files) and restarted Cura. 
Then when i loaded cura i got a much shorter list (sorry, did not screenshot it) and when i then disabled affected profiles - it worked. now cura 4.8 launches with no errors.  this is good news but i must say - i have no idea what are these errors for to begin with and why Cura tean can't get rid of these for many, many! years now. this is not a new issue - this is an old persisting issue which I wish i knew why we get those and what goes on under the hood.

Thx,

**Comment by fieldOfView** [comment]
Good to know you got it working, but now there's absolutely no way for me to reproduce this.
