### ISSUE TITLE
Saving 3mf file with plugin enabled causes Cura 4.8 to crash

### ISSUE THREAD

**Issue by g097103** [fieldOfView/Cura-StartOptimiser#4]
Went through troubleshooting and bug report with Cura who was able to reproduce the issue. Their solution analysis follows.

Indeed it is crashing when saving a project file. After further inspection, it seems to be caused by the Startup Optimizer plugin, because when I do "Extensions -> Startup Optimizer -> Restore all configuration files" and restart Cura, the problem no longer occurs. We do not maintain this plugin, so please post this issue in the github page of the Startup Optimizer.

**Comment by fieldOfView** [comment]
Could you point me to the original bugreport? Then I have a better chance of finding out what went wrong.

**Comment by fieldOfView** [comment]
Found it here:
https://github.com/Ultimaker/Cura/issues/8734

**Comment by fieldOfView** [comment]
Could you test if this still happens with version 3.5.1, which is now available in the Marketplace?

**Comment by g097103** [comment]
That seems to have fixed the problem, Thank you.

**Comment by fieldOfView** [comment]
Awesome!
