### ISSUE TITLE
Plugin not working in Cura 4.8

### ISSUE THREAD

**Issue by chipmunk1977** [fieldOfView/Cura-StartOptimiser#5]
Up til now the Startup Optimiser has always worked after an update.  After updating to Cura 4.8 it appears to have no effect.
Am using the Appimage file on Ubuntu Linux.  I tried removing the plugin and reinstalling it.  I selected Load only generic and custom materials, and got the message that 175 material would be skipped at the next restart.  After the restart the complete range of materials was still there.
In Cura 4.6.1, which i still have installed, the plugin works as expected.

**Comment by fieldOfView** [comment]
The plugin got broken by https://github.com/Ultimaker/Uranium/commit/af43da4586085d4c9ecdd1a28e342293f83a0748

Fixed in 386dd8e

I'll keep this issue open until a version of that plugin that includes the fix is available on the marketplace

**Comment by Sekisback** [comment]
thank you, i can confirm that it works again like expectetd. now ican use cura 4.8

**Comment by fieldOfView** [comment]
Version 3.5.1 of the plugin is now available in the Marketplace.
